// Records which catalogue tokens also trade on BingX, into
// shared/src/listings.ts.
//
//   pnpm --filter @sidik/engine listings
//
// Why this exists: a token you cannot sell cannot sustain a working market on
// an independent venue. A listing is therefore real corroboration of a PASS —
// and, if a token Sidik proves is a honeypot ever turns up listed, a finding
// worth shouting about. It is corroboration, never proof: Sidik's verdicts
// come from the fork and nowhere else.
//
// Matching is by HAND, not by ticker. Exchange symbols collide constantly —
// the catalogue and BingX share tickers like DOS, MON, SYS, HYPER and BSV
// that are certainly different assets — and claiming "this Base token is
// listed" about a different coin with the same three letters is exactly the
// kind of false claim this project exists to argue against. Only pairs
// verified as the same asset appear below.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Hex } from "@sidik/shared";

const BINGX_SYMBOLS = "https://open-api.bingx.com/openApi/spot/v1/common/symbols";

// address -> the ticker that is unambiguously this same asset.
const VERIFIED: [Hex, string][] = [
  ["0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", "USDC"],
  ["0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb", "DAI"],
  ["0x940181a94A35A4569E4529A3CDfB74e38FD98631", "AERO"],
  ["0x532f27101965dd16442E59d40670FaF5eBB142E4", "BRETT"],
  ["0xAC1Bd2486aAf3B5C0fc3Fd868558b082a531B2B4", "TOSHI"],
  ["0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed", "DEGEN"],
  ["0x9a26F5433671751C3276a065f57e5a02D2817973", "KEYCAT"],
  ["0xB1a03EdA10342529bBF8EB700a06C60441fEf25d", "MIGGLES"],
  ["0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b", "VIRTUAL"],
  ["0x0578d8A44db98B23BF096A382e016e29a5Ce0ffe", "HIGHER"],
];

const res = await fetch(BINGX_SYMBOLS, { headers: { "user-agent": "sidik" } });
if (!res.ok) throw new Error(`BingX returned ${res.status}`);
const body = await res.json() as { data?: { symbols?: { symbol: string }[] } };
const listed = new Set(
  (body.data?.symbols ?? []).map((s) => s.symbol.split("-")[0]!.toUpperCase()),
);
process.stderr.write(`BingX lists ${listed.size} spot assets\n`);

const confirmed: [Hex, string][] = [];
for (const [address, ticker] of VERIFIED) {
  const ok = listed.has(ticker.toUpperCase());
  process.stderr.write(`  ${ticker.padEnd(9)} ${ok ? "listed" : "not listed"}\n`);
  if (ok) confirmed.push([address, ticker]);
}

const out = fileURLToPath(new URL("../../shared/src/listings.ts", import.meta.url));
writeFileSync(out, `// GENERATED by engine/scripts/gen-listings.mts — do not edit by hand.
// Catalogue tokens confirmed to also trade on BingX, matched by hand rather
// than by ticker because exchange symbols collide. Corroboration only: a
// token you cannot sell cannot sustain a market on an independent venue.
// Verdicts still come from the fork and nowhere else.
import type { Hex } from "./types";

export const LISTED_ON_BINGX: Record<string, string> = ${
  JSON.stringify(Object.fromEntries(confirmed.map(([a, t]) => [a.toLowerCase(), t])), null, 2)
};

export function listedTicker(address: Hex | string): string | undefined {
  // Object.hasOwn, not a bare index. A plain object literal inherits from
  // Object.prototype, so LISTED_ON_BINGX["constructor"] returns a function
  // rather than undefined — as do __proto__, toString, valueOf and
  // hasOwnProperty. Every caller today passes a regex-validated address, so
  // this is not reachable; it becomes reachable the moment one does not, and
  // the caller would get a function where it expected a ticker.
  const key = String(address).toLowerCase();
  return Object.hasOwn(LISTED_ON_BINGX, key) ? LISTED_ON_BINGX[key] : undefined;
}
`);
process.stderr.write(`\nwrote ${confirmed.length} confirmed listing(s) -> ${out}\n`);
