// Names every PUSH4 selector found in the recorded catalogue's bytecodes and
// freezes them into src/selectorNames.ts.
//
//   pnpm --filter @sidik/engine selector-names
//
// The owner-trap probe reports the switches it could not name as "N
// selectors unnamed". A named absence — "found setMaxWallet(uint256), not
// operated" — is a different statement from an unnamed one, and the names
// are public: the 4byte signature database (api.4byte.sourcify.dev, the
// successor to openchain's lookup) resolves them without a key.
//
// Requires BASE_ARCHIVE_RPC. Reads one eth_getCode per recorded address at
// the fork block, then resolves in batches of 50 with a 300ms gap.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createPublicClient, http } from "viem";
import { base } from "viem/chains";
import { FIXTURES, FIXTURE_BLOCK } from "@sidik/shared";
import type { Hex } from "@sidik/shared";
import { selectorsIn } from "../src/selectors.js";

const OUT = fileURLToPath(new URL("../src/selectorNames.ts", import.meta.url));
const LOOKUP = "https://api.4byte.sourcify.dev/signature-database/v1/lookup";
const BATCH = 50;
const GAP_MS = 300;

const rpc = process.env.BASE_ARCHIVE_RPC;
if (!rpc) { console.error("BASE_ARCHIVE_RPC is required"); process.exit(2); }
const pub = createPublicClient({ chain: base, transport: http(rpc, { retryCount: 5, retryDelay: 800 }) });
const block = BigInt(FIXTURE_BLOCK);

const all = new Set<string>();
const addresses = Object.keys(FIXTURES) as Hex[];
let done = 0;
for (const address of addresses) {
  try {
    const code = await pub.getCode({ address, blockNumber: block });
    for (const s of selectorsIn(code ?? "0x")) all.add(s.toLowerCase());
  } catch (e) {
    console.error(`getCode ${address}: ${String(e).slice(0, 80)}`);
  }
  if (++done % 20 === 0) process.stderr.write(`  ${done}/${addresses.length} bytecodes, ${all.size} selectors\n`);
}
console.error(`${all.size} distinct selectors across ${addresses.length} bytecodes`);

const names: Record<string, string> = {};
const selectors = [...all].sort();
for (let i = 0; i < selectors.length; i += BATCH) {
  const chunk = selectors.slice(i, i + BATCH);
  const res = await fetch(`${LOOKUP}?function=${chunk.join(",")}&filter=true`);
  if (!res.ok) { console.error(`lookup ${i}: HTTP ${res.status}`); continue; }
  const body = (await res.json()) as { ok: boolean; result?: { function?: Record<string, { name: string; filtered: boolean }[] | null> } };
  for (const [sel, hits] of Object.entries(body.result?.function ?? {})) {
    const first = hits?.find((h) => !h.filtered) ?? hits?.[0];
    if (first) names[sel.toLowerCase()] = first.name;
  }
  process.stderr.write(`  ${Math.min(i + BATCH, selectors.length)}/${selectors.length} looked up, ${Object.keys(names).length} named\n`);
  await new Promise((r) => setTimeout(r, GAP_MS));
}

const sorted = Object.fromEntries(Object.entries(names).sort(([a], [b]) => a.localeCompare(b)));
writeFileSync(OUT, `// GENERATED by engine/scripts/gen-selector-names.mts — do not edit by hand.
// Every PUSH4 selector found across the ${addresses.length} recorded bytecodes at block
// ${FIXTURE_BLOCK}, named through the 4byte signature database
// (api.4byte.sourcify.dev). ${Object.keys(sorted).length} of ${selectors.length} resolved. Regenerate with:
//
//   pnpm --filter @sidik/engine selector-names
//
export const SELECTOR_NAMES: Record<string, string> = ${JSON.stringify(sorted, null, 2)};

/** The public name of a 4-byte selector, when the signature database has one. */
export function nameOf(selector: string): string | undefined {
  return SELECTOR_NAMES[selector.toLowerCase()];
}
`);
console.error(`wrote ${OUT}: ${Object.keys(sorted).length} names`);
