// Regenerates src/fixtures.json by actually running each example token
// against a real fork. Run it after changing EXAMPLES or BASE_FORK_BLOCK:
//
//   pnpm --filter @sidik/engine fixtures
//
// Requires BASE_ARCHIVE_RPC (and AI_GATEWAY_API_KEY if you want the LLM
// narration baked in rather than the template fallback).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { EXAMPLES } from "@sidik/shared";
import { isProbeFailure, runSidik } from "../src/orchestrator.js";
import { BASE_FORK_BLOCK } from "../src/examples.js";
import type { PreScan, Verdict } from "@sidik/shared";

const runs: Record<string, unknown> = {};

for (const ex of EXAMPLES) {
  process.stderr.write(`${ex.label} (${ex.address}) ... `);
  let scan: PreScan | undefined;
  let ids: string[] = [];
  const verdicts: Verdict[] = [];
  let narration = "";
  let failed: string | undefined;

  // Bypass the cache: it is seeded from the fixtures file this script is
  // rewriting, so reading it would replay the previous run instead of
  // producing a new one — including a previously frozen broken run, which
  // could then never be regenerated.
  for await (const ev of runSidik(ex.address, { getCached: () => undefined, setCached: () => {} })) {
    if (ev.type === "prescan") scan = ev.scan;
    else if (ev.type === "plan") ids = ev.ids;
    else if (ev.type === "verdict") verdicts.push(ev.verdict);
    else if (ev.type === "narration") narration = ev.text;
    else if (ev.type === "error") failed = ev.message;
  }

  // A run that broke proves nothing, and freezing it would hand judges a
  // permanent failure no retry can clear. That includes a probe that threw
  // — an RPC 429 mid-fork surfaces as an NA verdict, not an error event, and
  // one slipped into the first generated fixture set looking like a finding.
  // Skip the token entirely; it then falls through to a live run like any
  // other address.
  const broken = verdicts.find(isProbeFailure);
  if (failed || !scan || broken) {
    process.stderr.write(`SKIPPED (${failed ?? broken?.title ?? "no prescan"})\n`);
    continue;
  }
  runs[ex.address.toLowerCase()] = { scan, ids, verdicts, narration };
  process.stderr.write(`${verdicts.map((v) => `${v.probe}=${v.status}`).join(" ")}\n`);
}

// Emitted into shared/ as TypeScript rather than engine-local JSON: web
// replays these as its offline demo and engine seeds them into its cache, and
// a hand-written stand-in for them drifted from reality twice.
const out = fileURLToPath(new URL("../../shared/src/fixtures.ts", import.meta.url));
const banner = `// GENERATED by engine/scripts/gen-fixtures.mts — do not edit by hand.
// Real output of real runs against a fork of Base at the block below. Engine
// seeds these into its cache so an example token needs no network; web
// replays them when no engine is configured. Regenerate with:
//
//   pnpm --filter @sidik/engine fixtures
//
import type { PreScan, Verdict } from "./types";

export interface FrozenRun {
  scan: PreScan;
  ids: string[];
  verdicts: Verdict[];
  narration: string;
}

// The fork block these were produced at. Bump BASE_FORK_BLOCK and they stop
// matching, so a stale run can never be passed off as proof about a new pin.
export const FIXTURE_BLOCK = "${BASE_FORK_BLOCK}";

export const FIXTURES: Record<string, FrozenRun> = `;
writeFileSync(out, banner + JSON.stringify(runs, null, 2) + ";\n");
process.stderr.write(`\nwrote ${Object.keys(runs).length} fixture(s) at block ${BASE_FORK_BLOCK} -> ${out}\n`);
