import type { NextRequest } from "next/server";
import type { Hex } from "@sidik/shared";
import type { RunEvent } from "@/lib/sse";
import { FIXTURES, FIXTURE_BLOCK } from "@sidik/shared";

export const runtime = "nodejs";

const encoder = new TextEncoder();
const sseFrame = (e: RunEvent) => encoder.encode(`event: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`);

export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get("token");
  if (!token) return new Response("token query param is required", { status: 400 });

  const engineUrl = process.env.ENGINE_URL;
  // ?replay=1 is a dev convenience only — a configured ENGINE_URL in
  // production must never be short-circuited by a query param.
  const forceReplay = req.nextUrl.searchParams.get("replay") === "1" && process.env.NODE_ENV !== "production";

  if (!engineUrl || forceReplay) {
    return new Response(replayStream(token as Hex), { headers: sseHeaders });
  }

  // Thin passthrough — no rewriting, just pipe the engine's SSE bytes straight through.
  const upstream = await fetch(`${engineUrl}/run?token=${encodeURIComponent(token)}`, {
    signal: req.signal,
  });
  return new Response(upstream.body, { status: upstream.status, headers: sseHeaders });
}

const sseHeaders = {
  "Content-Type": "text/event-stream",
  "Cache-Control": "no-cache, no-transform",
  Connection: "keep-alive",
};

// ---- offline replay ----------------------------------------------------
//
// With no engine configured, serve the frozen runs in @sidik/shared — real
// output of real fork runs, generated by `pnpm --filter @sidik/engine
// fixtures`. This used to be a hand-written script of invented verdicts,
// which drifted from what the engine actually proves twice over. Replaying
// recorded truth cannot drift.
//
// An address with no frozen run gets an honest error. Answering for an
// arbitrary token with no engine behind it would be making something up.

// Paced so the trace reads as a sequence of steps rather than appearing all
// at once. The delays are presentation, and nothing but presentation — every
// event below is verbatim from the recorded run.
const STEP_MS = 260;
const PROBE_MS = 620;

function replayStream(token: Hex): ReadableStream<Uint8Array> {
  const run = FIXTURES[token.toLowerCase()];

  const script: [number, RunEvent][] = run
    ? [
        [0, { type: "replay", block: FIXTURE_BLOCK }],
        [STEP_MS, { type: "prescan", scan: run.scan }],
        [STEP_MS, { type: "plan", ids: run.ids }],
        ...run.verdicts.flatMap((verdict): [number, RunEvent][] => [
          [STEP_MS, { type: "probe:start", id: verdict.probe }],
          [PROBE_MS, { type: "verdict", verdict }],
        ]),
        [STEP_MS, { type: "narration", text: run.narration }],
        [STEP_MS / 2, { type: "done" }],
      ]
    : [
        [0, { type: "replay", block: FIXTURE_BLOCK }],
        [STEP_MS, {
          type: "error",
          // Counted, not written down: the catalogue grows every time it is
          // re-recorded, and a hardcoded number would start lying immediately.
          message:
            `No engine is configured, so this address cannot be probed live. ` +
            `${Object.keys(FIXTURES).length} Base tokens have a recorded run — ` +
            `try one of the examples.`,
        }],
      ];

  let i = 0;
  return new ReadableStream({
    async pull(controller) {
      if (i >= script.length) {
        controller.close();
        return;
      }
      const [delayMs, event] = script[i++];
      await new Promise((r) => setTimeout(r, delayMs));
      controller.enqueue(sseFrame(event));
    },
  });
}
