// GENERATED by engine/scripts/gen-fixtures.mts — do not edit by hand.
// Real output of real runs against a fork of Base at the block below. Engine
// seeds these into its cache so a known token needs no network; web replays
// them when no engine is configured. Regenerate with:
//
//   SIDIK_CATALOG=120 pnpm --filter @sidik/engine fixtures
//
import type { PreScan, Verdict } from "./types";

export interface FrozenRun {
  scan: PreScan;
  ids: string[];
  verdicts: Verdict[];
  narration: string;
}

// The fork block these were produced at. Bump BASE_FORK_BLOCK and they stop
// matching, so a stale run can never be passed off as proof about a new pin.
export const FIXTURE_BLOCK = "50200000";

export const FIXTURES: Record<string, FrozenRun> = {
  "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913": {
    "scan": {
      "token": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      "isErc20": true,
      "symbol": "USDC",
      "decimals": 6,
      "hasPool": true,
      "poolAddress": "0x6c561B446416E1A00E8E93E221854d6eA4171372",
      "venue": "v3",
      "poolFee": 3000,
      "owner": "0x3ABd6f64A422225E61E435baE41db12096106df7",
      "topHolders": []
    },
    "ids": [
      "honeypot",
      "hiddenFee"
    ],
    "verdicts": [
      {
        "probe": "honeypot",
        "status": "PASS",
        "title": "Not a honeypot — buy and sell both succeed",
        "rows": [
          {
            "label": "Sell after buying",
            "claimed": "Freely tradable",
            "proven": "Sell succeeded",
            "ok": true
          }
        ],
        "numbers": {
          "boughtAmount": "2,251.43 USDC"
        },
        "txHashes": [
          "0xb42070a123bc9cd2d901584dd125ddb7dc804fd797b50c6c9c0991dd7b1f6680",
          "0x91b11af1e6b628bb58222a4b0a006f3724f81ab83be274a87b5a0b9b5520f1e3"
        ]
      },
      {
        "probe": "hiddenFee",
        "status": "PASS",
        "title": "No hidden fee on buying, selling or transferring",
        "rows": [
          {
            "label": "Buy through the pool",
            "claimed": "You receive the full quoted amount",
            "proven": "Received the full quoted amount",
            "ok": true
          },
          {
            "label": "Sell back through the pool",
            "claimed": "You receive the full quoted proceeds",
            "proven": "Proceeds matched the quote",
            "ok": true
          },
          {
            "label": "Transfer the full balance",
            "claimed": "Recipient gets 100%",
            "proven": "Recipient got 100%",
            "ok": true
          }
        ],
        "numbers": {
          "sent": "1,125.71 USDC",
          "received": "1,125.71 USDC",
          "feePct": "0%",
          "buyTaxPct": "0%",
          "sellTaxPct": "0%"
        },
        "txHashes": [
          "0xb42070a123bc9cd2d901584dd125ddb7dc804fd797b50c6c9c0991dd7b1f6680",
          "0x076e7fa99a65843c9c88ab9e6827728805412d3604ba7990377b7705e73d5011",
          "0x6dde339688fd43c18ed132903f46250d61946f1faeb01ff0e26390ee0dbf623b"
        ]
      }
    ],
    "narration": "Both executed probes passed. The honeypot check confirmed the token is freely tradable: a buy of 2,251.43 USDC was followed by a successful sell. The hidden fee check found no fees on buying, selling, or transferring — buy and sell tax were each 0%, and a transfer of 1,125.71 USDC arrived with the recipient receiving the full 1,125.71 USDC (100%). No discrepancies were found between claimed and proven outcomes across any of the tested actions."
  }
};

export const FIXTURE_COUNT = 1;
