// GENERATED by engine/scripts/gen-fixtures.mts — do not edit by hand.
// Real output of real runs against a fork of Base at the block below. Engine
// seeds these into its cache so an example token needs no network; web
// replays them when no engine is configured. Regenerate with:
//
//   pnpm --filter @sidik/engine fixtures
//
import type { PreScan, Verdict } from "./types";

export interface FrozenRun {
  scan: PreScan;
  ids: string[];
  verdicts: Verdict[];
  narration: string;
}

// The fork block these were produced at. Bump BASE_FORK_BLOCK and they stop
// matching, so a stale run can never be passed off as proof about a new pin.
export const FIXTURE_BLOCK = "50200000";

export const FIXTURES: Record<string, FrozenRun> = {
  "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913": {
    "scan": {
      "token": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      "isErc20": true,
      "symbol": "USDC",
      "decimals": 6,
      "hasPool": true,
      "poolAddress": "0x88A43bbDF9D098eEC7bCEda4e2494615dfD9bB9C",
      "owner": "0x3ABd6f64A422225E61E435baE41db12096106df7",
      "topHolders": []
    },
    "ids": [
      "honeypot",
      "hiddenFee",
      "lpRug"
    ],
    "verdicts": [
      {
        "probe": "honeypot",
        "status": "PASS",
        "title": "Not a honeypot — buy and sell both succeed",
        "rows": [
          {
            "label": "Sell after buying",
            "claimed": "Freely tradable",
            "proven": "Sell succeeded",
            "ok": true
          }
        ],
        "numbers": {
          "boughtAmount": "2240708453"
        },
        "txHashes": [
          "0xd9819fef94ebf6f11648510e08fe0292c99bf36debf892284a462e3a85123fb6",
          "0x893a08057d9d195c42fc926c0ba8a80d46aa00eb4fc42bae0a7da548fc38d617"
        ]
      },
      {
        "probe": "hiddenFee",
        "status": "PASS",
        "title": "No hidden fee on buying or transferring",
        "rows": [
          {
            "label": "Buy through the pool",
            "claimed": "You receive the full quoted amount",
            "proven": "Received the full quoted amount",
            "ok": true
          },
          {
            "label": "Transfer 100% of tokens",
            "claimed": "Recipient gets 100%",
            "proven": "Recipient got 100%",
            "ok": true
          }
        ],
        "numbers": {
          "sent": "2240708453",
          "received": "2240708453",
          "feePct": "0%",
          "buyTaxPct": "0%"
        },
        "txHashes": [
          "0xd9819fef94ebf6f11648510e08fe0292c99bf36debf892284a462e3a85123fb6",
          "0xff9634a0c89f16922926eb34dc8feed5109a24ccb75ee155e06e96c4244f27a7"
        ]
      },
      {
        "probe": "lpRug",
        "status": "NA",
        "title": "LP is not burned (0%) and its holder could not be identified",
        "rows": [
          {
            "label": "LP owner can drain the pool",
            "claimed": "Liquidity is locked/safe",
            "proven": "Only 0% of LP is burned, so someone can still withdraw it — but no holder could be identified",
            "ok": false
          }
        ],
        "numbers": {
          "ownerLpPct": "0%",
          "burnedLpPct": "0%",
          "holderValueBefore": "0",
          "holderValueAfter": "0",
          "lpOwner": "0x0000000000000000000000000000000000000000"
        },
        "txHashes": []
      }
    ],
    "narration": "✓ Not a honeypot — buy and sell both succeed\n✓ No hidden fee on buying or transferring\n— LP is not burned (0%) and its holder could not be identified"
  },
  "0x48f617e5b1b214a90800348d7944bbc0e9290fbb": {
    "scan": {
      "token": "0x48F617e5b1B214a90800348D7944bBc0E9290Fbb",
      "isErc20": true,
      "symbol": "Anastasia",
      "decimals": 8,
      "hasPool": true,
      "poolAddress": "0xDB4B1756e5B26E523228bf7566A58a8D5F7527dC",
      "owner": "0x0000000000000000000000000000000000000000",
      "topHolders": []
    },
    "ids": [
      "honeypot",
      "hiddenFee",
      "lpRug"
    ],
    "verdicts": [
      {
        "probe": "honeypot",
        "status": "FAIL",
        "title": "Honeypot — you can buy but cannot sell",
        "rows": [
          {
            "label": "Sell after buying",
            "claimed": "Freely tradable",
            "proven": "Sell reverted",
            "ok": false
          }
        ],
        "numbers": {
          "boughtAmount": "2788707521021"
        },
        "txHashes": [
          "0xf6712fd40e528cad82f830ca6a5d0c3c34186ac9bba49cf60d8732b01ce189ee",
          "0x60aaa0d22f4ff4f62f7a6e7ae36cdb538e48a400f7f8fe26429cfe361cd9afac"
        ],
        "reason": "Execution reverted with reason: TransferHelper: TRANSFER_FROM_FAILED."
      },
      {
        "probe": "hiddenFee",
        "status": "PASS",
        "title": "No hidden fee on buying or transferring",
        "rows": [
          {
            "label": "Buy through the pool",
            "claimed": "You receive the full quoted amount",
            "proven": "Received the full quoted amount",
            "ok": true
          },
          {
            "label": "Transfer 100% of tokens",
            "claimed": "Recipient gets 100%",
            "proven": "Recipient got 100%",
            "ok": true
          }
        ],
        "numbers": {
          "sent": "2788707521021",
          "received": "2788707521021",
          "feePct": "0%",
          "buyTaxPct": "0%"
        },
        "txHashes": [
          "0xf6712fd40e528cad82f830ca6a5d0c3c34186ac9bba49cf60d8732b01ce189ee",
          "0xabd3c2e54d8ba70ba35a236819282210676051ed6584f6d99069e2db3e322e4b"
        ]
      },
      {
        "probe": "lpRug",
        "status": "NA",
        "title": "LP is not burned (0%) and its holder could not be identified",
        "rows": [
          {
            "label": "LP owner can drain the pool",
            "claimed": "Liquidity is locked/safe",
            "proven": "Only 0% of LP is burned, so someone can still withdraw it — but no holder could be identified",
            "ok": false
          }
        ],
        "numbers": {
          "ownerLpPct": "0%",
          "burnedLpPct": "0%",
          "holderValueBefore": "0",
          "holderValueAfter": "0",
          "lpOwner": "0x0000000000000000000000000000000000000000"
        },
        "txHashes": []
      }
    ],
    "narration": "⚠️ Honeypot — you can buy but cannot sell\n✓ No hidden fee on buying or transferring\n— LP is not burned (0%) and its holder could not be identified"
  },
  "0x0e86efe5ba52336c2173ad69ee726e054619e0d8": {
    "scan": {
      "token": "0x0e86eFe5Ba52336c2173AD69EE726e054619e0d8",
      "isErc20": true,
      "symbol": "BRB",
      "decimals": 18,
      "hasPool": true,
      "poolAddress": "0x7B7E7a86bb5c39769f8385F403E1d3Fc83678225",
      "owner": "0x936960b3844a80038B5A50e2064cC29eC6dB64d4",
      "topHolders": []
    },
    "ids": [
      "honeypot",
      "hiddenFee",
      "lpRug"
    ],
    "verdicts": [
      {
        "probe": "honeypot",
        "status": "PASS",
        "title": "Not a honeypot — buy and sell both succeed",
        "rows": [
          {
            "label": "Sell after buying",
            "claimed": "Freely tradable",
            "proven": "Sell succeeded",
            "ok": true
          }
        ],
        "numbers": {
          "boughtAmount": "10702235470409660775853120"
        },
        "txHashes": [
          "0x1d379f78e938535ded53499b16ef77ea7c443953e173fac534b696238567dd53",
          "0x7f4a42678be71c030beb013a49a153073e3854864df0d87ed25a9ae41919caa1"
        ]
      },
      {
        "probe": "hiddenFee",
        "status": "FAIL",
        "title": "Hidden buy tax of 2.99%",
        "rows": [
          {
            "label": "Buy through the pool",
            "claimed": "You receive the full quoted amount",
            "proven": "Received 2.99% less than the pool's own quote",
            "ok": false
          },
          {
            "label": "Transfer 100% of tokens",
            "claimed": "Recipient gets 100%",
            "proven": "Recipient got 100%",
            "ok": true
          }
        ],
        "numbers": {
          "sent": "10702235470409660775853120",
          "received": "10702235470409660775853120",
          "feePct": "0%",
          "buyTaxPct": "2.99%"
        },
        "txHashes": [
          "0x1d379f78e938535ded53499b16ef77ea7c443953e173fac534b696238567dd53",
          "0x27acae28dd1fe5f8f811be960efd26127eb6c7aad93415fc838fc1dbcb789898"
        ]
      },
      {
        "probe": "lpRug",
        "status": "PASS",
        "title": "LP is burned — 99.98% of it cannot be withdrawn by anyone",
        "rows": [
          {
            "label": "LP owner can drain the pool",
            "claimed": "Liquidity is locked/safe",
            "proven": "99.98% of LP supply sits at a burn address, beyond any owner's reach",
            "ok": true
          }
        ],
        "numbers": {
          "ownerLpPct": "0%",
          "burnedLpPct": "99.98%",
          "holderValueBefore": "0",
          "holderValueAfter": "0",
          "lpOwner": "0x0000000000000000000000000000000000000000"
        },
        "txHashes": []
      }
    ],
    "narration": "✓ Not a honeypot — buy and sell both succeed\n⚠️ Hidden buy tax of 2.99%\n✓ LP is burned — 99.98% of it cannot be withdrawn by anyone"
  }
};
