// GENERATED by engine/scripts/gen-listings.mts — do not edit by hand.
// Catalogue tokens confirmed to also trade on BingX, matched by hand rather
// than by ticker because exchange symbols collide. Corroboration only: a
// token you cannot sell cannot sustain a market on an independent venue.
// Verdicts still come from the fork and nowhere else.
import type { Hex } from "./types";

export const LISTED_ON_BINGX: Record<string, string> = {
  "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913": "USDC",
  "0x50c5725949a6f0c72e6c4a641f24049a917db0cb": "DAI",
  "0x940181a94a35a4569e4529a3cdfb74e38fd98631": "AERO",
  "0x532f27101965dd16442e59d40670faf5ebb142e4": "BRETT",
  "0xac1bd2486aaf3b5c0fc3fd868558b082a531b2b4": "TOSHI",
  "0x4ed4e862860bed51a9570b96d89af5e1b0efefed": "DEGEN",
  "0x9a26f5433671751c3276a065f57e5a02d2817973": "KEYCAT",
  "0xb1a03eda10342529bbf8eb700a06c60441fef25d": "MIGGLES",
  "0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b": "VIRTUAL",
  "0x0578d8a44db98b23bf096a382e016e29a5ce0ffe": "HIGHER"
};

export function listedTicker(address: Hex | string): string | undefined {
  // Object.hasOwn, not a bare index. A plain object literal inherits from
  // Object.prototype, so LISTED_ON_BINGX["constructor"] returns a function
  // rather than undefined — as do __proto__, toString, valueOf and
  // hasOwnProperty. Every caller today passes a regex-validated address, so
  // this is not reachable; it becomes reachable the moment one does not, and
  // the caller would get a function where it expected a ticker.
  const key = String(address).toLowerCase();
  return Object.hasOwn(LISTED_ON_BINGX, key) ? LISTED_ON_BINGX[key] : undefined;
}
