// GENERATED by engine/scripts/recheck.mts — do not edit by hand.
// Merge-on-write: each recheck run adds or replaces its own addresses.
//
//   pnpm --filter @sidik/engine recheck COBIE KEYCAT NVO CASHCAT
//
// The honeypot probe, re-executed against a fork of Base at the head block of
// the day it ran, for addresses whose recorded verdict a read-only scanner
// disputes. The recorded verdict describes block 50,200,000; a scanner reading
// describes the day it was asked; this is the only thing that tells "the
// token changed since the pin" from "the scanner is wrong".
//
// Context, never evidence: nothing here changes a recorded verdict.

export interface Recheck {
  /** The head block the fork was taken at (head − 20, so it cannot reorg away). */
  headBlock: string;
  /** ISO date the recheck ran. */
  checkedOn: string;
  /** Honeypot probe status at that head. */
  status: "PASS" | "FAIL" | "NA";
  /** The probe's one-line verdict at that head. */
  title: string;
}

export const RECHECKS: Record<string, Recheck> = {
  "0x48f617e5b1b214a90800348d7944bbc0e9290fbb": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "FAIL",
    "title": "Honeypot — you can buy but cannot sell"
  },
  "0xfd2cc6b7af94c209a6221a134ac4b3924e1e84ab": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0x8f92c14757ebf6298dd5be033a179d01f6794696": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0xe22f1468de1dbc629c599926f637d4fa119aee41": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0x320238f952412b7a7dc0eefa45a503c62571afd3": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0xffd7ab897caaa6114fe055d624832311346c2a02": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0x688623465a6d3d60958022d55c9fdc987640f0e3": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0x8fab908211812cfa52d34bf0efe066bd9d01f732": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0x9a26f5433671751c3276a065f57e5a02d2817973": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0x3329c0315f6a0c0787d94755de083ef625fa5b6b": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "PASS",
    "title": "Not a honeypot — buy and sell both succeed"
  },
  "0x87605cccb17bc26111059ec9c4d5ec88fc0b5da6": {
    "headBlock": "50572271",
    "checkedOn": "2026-08-28",
    "status": "FAIL",
    "title": "Cannot sell — the token skims 6.99% off every transfer, and Uniswap V3 rejects a token that arrives short"
  },
  "0x0480dfeb876221ad9ab90d4687efd6d5d6c839c2": {
    "headBlock": "50579458",
    "checkedOn": "2026-08-28",
    "status": "FAIL",
    "title": "Pool holds 3.2 WETH but the buy reverted (Execution reverted with reason: UniswapV2: TRANSFER_FAILED.)"
  }
};

/** The head-of-day recheck for an address, if one was run. */
export function recheckOf(address: string): Recheck | undefined {
  const key = String(address).toLowerCase();
  // hasOwn, not a bare lookup: "constructor" is a key on every object, and
  // the run page hands this result to a client component — a function there
  // is a render error, not a 404.
  return Object.hasOwn(RECHECKS, key) ? RECHECKS[key] : undefined;
}
